=== Tsukoyachi/RecipeRhapsody/xml2json/outputSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "orderId": {
      "type": "string",
      "minLength": 1
    },
    "customer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "address": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": ["name", "address"]
    },
    "content": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "recipeId": {
            "type": "string",
            "minLength": 1
          },
          "pricePerUnity": {
            "type": "number",
            "multipleOf": 0.01,
            "minimum": 0
          },
          "quantity": {
            "type": "integer"
          }
        },
        "required": ["recipeId", "pricePerUnity", "quantity"]
      }
    },
    "totalPrice": {
      "type": "number",
      "multipleOf": 0.01,
      "minimum": 0
    }
  },
  "required": ["orderId", "customer", "content", "totalPrice"]
}

=== Tsukoyachi/RecipeRhapsody/xml2json/output.json
{
  "$schema" : "./outputSchema.json",
  "orderId": "b934abac0d4c44e7afaafd4035fdccd0",
  "customer": {
    "name": "Axel Delille",
    "address": "200 Avenue Roumanille, 06560 Valbonne"
  },
  "content": [
    {
      "recipeId": "ed59c15adb99471eba2ef1a76d106b2b",
      "pricePerUnity": 8.99,
      "quantity": 1
    },
    {
      "recipeId": "bcd32a9fe07b4f93949714d7d374dbe6",
      "pricePerUnity": 13.99,
      "quantity": 3
    }
  ],
  "totalPrice": 50.96
}
