=== Tsukoyachi/RecipeRhapsody/htmlScenario/common/recipeBook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="recipeBook" type="RecipeBookType">
        <xs:key name="recipeId">
            <xs:selector xpath="./recipes/recipe"/>
            <xs:field xpath="@recipeId"/>
        </xs:key>

        <xs:keyref name="recipeIdRef" refer="recipeId">
            <xs:selector xpath="./orders/order/recipes/recipe"/>
            <xs:field xpath="@recipeId"/>
        </xs:keyref>

        <xs:key name="userId">
            <xs:selector xpath="./users/user"/>
            <xs:field xpath="@userId"/>
        </xs:key>

        <xs:keyref name="userIdRef" refer="userId">
            <xs:selector xpath="./recipes/recipe/userRatings/userRate"/>
            <xs:field xpath="@userId"/>
        </xs:keyref>

        <xs:key name="deliveryId">
            <xs:selector xpath="./deliveryMans/deliveryMan"/>
            <xs:field xpath="@deliveryId"/>
        </xs:key>

        <xs:keyref name="deliveryIdRef" refer="deliveryId">
            <xs:selector xpath="./orders/order"/>
            <xs:field xpath="@deliveryId"/>
        </xs:keyref>

        <xs:key name="ingredientId">
            <xs:selector xpath="./ingredients/ingredient"/>
            <xs:field xpath="@ingredientId"/>
        </xs:key>

        <xs:keyref name="ingredientIdRef" refer="ingredientId">
            <xs:selector xpath="./recipes/recipe/ingredients/ingredient"/>
            <xs:field xpath="@ingredientId"/>
        </xs:keyref>

        <xs:key name="allergenId">
            <xs:selector xpath="./allergens/allergen"/>
            <xs:field xpath="@allergenId"/>
        </xs:key>

        <xs:keyref name="allergenIdRef" refer="allergenId">
            <xs:selector xpath="./recipes/recipe/allergens/allergen"/>
            <xs:field xpath="@allergenId"/>
        </xs:keyref>

        <xs:key name="toolId">
            <xs:selector xpath="./tools/tool"/>
            <xs:field xpath="@toolId"/>
        </xs:key>

        <xs:keyref name="toolIdRef" refer="toolId">
            <xs:selector xpath="./recipes/recipe/tools/tool"/>
            <xs:field xpath="@toolId"/>
        </xs:keyref>

        <xs:key name="orderId">
            <xs:selector xpath="./orders/order"/>
            <xs:field xpath="@orderId"/>
        </xs:key>
    </xs:element>

    <xs:complexType name="RecipeBookType">
        <xs:sequence>
            <xs:element name="recipes" type="RecipesType" minOccurs="0"/>
            <xs:element name="users" type="UsersBaseType" minOccurs="0"/>
            <xs:element name="deliveryMan" type="DeliveryMansBaseType" minOccurs="0"/>
            <xs:element name="ingredients" type="IngredientsBaseType" minOccurs="0"/>
            <xs:element name="tools" type="ToolsBaseType" minOccurs="0"/>
            <xs:element name="allergens" type="AllergensBaseType" minOccurs="0"/>
            <xs:element name="orders" type="OrdersType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RecipesType">
        <xs:sequence>
            <xs:element name="recipe" type="RecipeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RecipeType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="image" type="xs:string" minOccurs="0"/>
            <xs:element name="ingredients" type="IngredientsType"/>
            <xs:element name="allergens" type="AllergensType" minOccurs="0"/>
            <xs:element name="tools" type="ToolsType" minOccurs="0"/>
            <xs:element name="steps" type="StepsType" minOccurs="0"/>
            <xs:element name="userRatings" type="UserRatingsType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="recipeId" type="xs:ID" use="required"/>
        <xs:attribute name="price" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="0.01"/>
                    <xs:fractionDigits value="2"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="IngredientsType">
        <xs:sequence>
            <xs:element name="ingredient" type="IngredientType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="IngredientType">
        <xs:sequence>
            <xs:element name="quantity" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="ingredientId" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="AllergensType">
        <xs:sequence>
            <xs:element name="allergen" type="AllergenType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AllergenType">
        <xs:attribute name="allergenId" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="ToolsType">
        <xs:sequence>
            <xs:element name="tool" type="ToolType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ToolType">
        <xs:attribute name="toolId" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="StepsType">
        <xs:sequence>
            <xs:element name="step" type="StepType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="StepType">
        <xs:sequence>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="photo" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="UserRatingsType">
        <xs:sequence>
            <xs:element name="userRate" type="UserRatingType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="UserRatingType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="userId" type="xs:IDREF" use="required"/>
                <xs:attribute name="grade">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="5"/>
                            <xs:fractionDigits value="1"/>
                            <xs:totalDigits value="2"/>
                            <xs:pattern value="[0-5](\.[05])?"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="UsersBaseType">
        <xs:sequence>
            <xs:element name="user" type="UserBaseType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="UserBaseType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="userId" type="xs:ID"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="IngredientsBaseType">
        <xs:sequence>
            <xs:element name="ingredient" type="IngredientBaseType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DeliveryMansBaseType">
        <xs:sequence>
            <xs:element name="deliveryMan" type="DeliveryManBaseType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DeliveryManBaseType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="deliveryId" type="xs:ID"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="IngredientBaseType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="ingredientId" type="xs:ID" use="required"/>
                <xs:attribute name="category" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="cereals"/>
                            <xs:enumeration value="vegetables"/>
                            <xs:enumeration value="seasoning"/>
                            <xs:enumeration value="fish"/>
                            <xs:enumeration value="meat"/>
                            <xs:enumeration value="fruit"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="season" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="spring"/>
                            <xs:enumeration value="summer"/>
                            <xs:enumeration value="autumn"/>
                            <xs:enumeration value="winter"/>
                            <xs:enumeration value="all"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:complexType name="ToolsBaseType">
        <xs:sequence>
            <xs:element name="tool" type="ToolBaseType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ToolBaseType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="toolId" type="xs:ID" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="AllergensBaseType">
        <xs:sequence>
            <xs:element name="allergen" type="AllergenBaseType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AllergenBaseType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="allergenId" type="xs:ID" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="OrdersType">
        <xs:sequence>
            <xs:element name="order" type="OrderType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OrderType">
        <xs:sequence>
            <xs:element name="recipes" type="OrderRecipesType"/>
            <xs:element name="address" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="userId" type="xs:IDREF" use="required"/>
        <xs:attribute name="deliveryManId" type="xs:IDREF" use="required"/>
        <xs:attribute name="orderId" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="OrderRecipesType">
        <xs:sequence>
            <xs:element name="recipe" type="OrderRecipeType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OrderRecipeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="recipeId" type="xs:IDREF" use="required"/>
                <xs:attribute name="quantity" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:minInclusive value="1"/>
                            <xs:fractionDigits value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== Tsukoyachi/RecipeRhapsody/recipeBook.xml
<?xml version="1.0" encoding="UTF-8"?>
<recipeBook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recipeBook.xsd">
    <recipes>
        <recipe>
            <name>Pesto pasta</name>
            <ingredients>
                <ingredient ingredientId="1">
                    <quantity>80g</quantity>
                </ingredient>
                <ingredient ingredientId="2">
                    <quantity>3 table spoon</quantity>
                </ingredient>
            </ingredients>
            <userRatings>
                <userRate userId="1">Easy and efficient</userRate>
            </userRatings>
        </recipe>
    </recipes>

    <users>
        <user userId="1">Axel Delille</user>
    </users>

    <ingredients>
        <ingredient ingredientId="1">
            <name>Pasta</name>
        </ingredient>
        <ingredient ingredientId="2">
            <name>Pesto</name>
        </ingredient>
    </ingredients>
</recipeBook>

=== Tsukoyachi/RecipeRhapsody/htmlScenario/filterByAllergen/recipeBook.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="filterByAllergen.xsl"?>
<recipeBook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recipeBook.xsd">
    <recipes>
        <recipe>
            <name>Pesto pasta</name>
            <image>https://assets.afcdn.com/recipe/20130924/64004_w1024h576c1cx3456cy2304.jpg</image>
            <ingredients>
                <ingredient ingredientId="1">
                    <quantity>180g</quantity>
                </ingredient>
                <ingredient ingredientId="2">
                    <quantity>100g</quantity>
                </ingredient>
                <ingredient ingredientId="3">
                    <quantity>2 tablespoon</quantity>
                </ingredient>
                <ingredient ingredientId="4">
                    <quantity>1 large</quantity>
                </ingredient>
                <ingredient ingredientId="5">
                    <quantity>150g</quantity>
                </ingredient>
                <ingredient ingredientId="6">
                    <quantity>150g</quantity>
                </ingredient>
                <ingredient ingredientId="7">
                    <quantity>1 heaped tablespoon</quantity>
                </ingredient>
                <ingredient ingredientId="8">
                    <quantity>1</quantity>
                </ingredient>
            </ingredients>
            <allergens>
                <!-- <allergen allergenId="1"/> -->
            </allergens>
            <tools>
                <tool toolId="1"/>
            </tools>
            <steps>
                <step>
                    <description>Bring a pan of lightly salted water to the boil. Add the broccoli and boil for 1 min 30 secs, or until tender. Drain and set aside. Cook the spaghetti following pack instructions, then drain, reserving a ladleful of cooking water.</description>
                    <photo>https://www.wikihow.com/images/thumb/d/d0/Boil-Water-Step-8-Version-9.jpg/v4-460px-Boil-Water-Step-8-Version-9.jpg</photo>
                </step>
                <step>
                    <description>Heat the oil in a large frying pan, add the garlic clove and fry over a low heat for 2 mins. Remove with a slotted spoon and discard, leaving the flavoured oil.</description>
                    <photo>https://www.allrecipes.com/thmb/BD9DhdanpJsrBu6rHK7EFrRkBGU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/how-to-roast-garlic-in-pan-ar-2000-7bec42d9517e4cab9db93619a5bba52d.jpg</photo>
                </step>
                <step>
                    <description>Add the tomatoes to the pan and fry over a medium heat for 5 mins, or until beginning to soften and turn juicy. Stir through the prawns and cook for 2 mins, or until turning pink. Add the harissa and lemon zest, stirring to coat.</description>
                    <photo>https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2021/07/How-to-Make-Blistered-Tomatoes-1.jpg</photo>
                </step>
                <step>
                    <description>Toss the cooked spaghetti and pasta water through the prawns and harissa. Stir through the broccoli, season to taste and serve.</description>
                    <photo>https://images.immediate.co.uk/production/volatile/sites/30/2020/08/prawn-harissa-spaghetti-d29786f.jpg?resize=768,574</photo>
                </step>
            </steps>
            <userRatings>
                <userRate userId="1" grade="4.5">Easy and efficient</userRate>
            </userRatings>
        </recipe>
    </recipes>

    <users>
        <user userId="1">Axel Delille</user>
    </users>

    <ingredients>
        <ingredient ingredientId="1">pasta</ingredient>
        <ingredient ingredientId="2">long-stem broccoli</ingredient>
        <ingredient ingredientId="3">olive oil</ingredient>
        <ingredient ingredientId="4">garlic clove</ingredient>
        <ingredient ingredientId="5">cherry tomatoes</ingredient>
        <ingredient ingredientId="6">raw king prawns</ingredient>
        <ingredient ingredientId="7">rose harissa paste</ingredient>
        <ingredient ingredientId="8">lemon</ingredient>
    </ingredients>

    <tools>
        <tool toolId="1">pan</tool>
        <tool toolId="2">frying pan</tool>
    </tools>

    <allergens>
        <allergen allergenId="1">gluten</allergen>
    </allergens>
</recipeBook>
